name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_MY_REGISTRY_INDEX: https://github.com/rust-lang/crates.io-index

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
      - name: Check code format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
      - run: cargo clippy --all-targets --all-features -- -D warnings


  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2023-04-07
      - uses: actions/checkout@v2
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2023-04-07
      - uses: actions/checkout@v2
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features --no-fail-fast
